### ISSUE TITLE
Decouple pricing

### ISSUE THREAD

**Issue by marcusklaas** [JordyMoos/JMSuperDeal#13]
Moos, I was thinking a bit about this program. 

Would it make sense to introduce an add-on that only computes a suggested sale price for a given item? The only thing the JMSuperDeal addon should need to identify super deals is the current listing price and the "optimal" listing price. The way this optimal price is determined need not be the responsibility of this add-on.

If this functionality is decoupled, we could re-use it when we are selling items. Currently, we need to keep track of our purchases and their intended resale price by hand. If we have an add-on that can compute the suggested selling price, this bookkeeping is no longer required. Instead, we just fire up the JMSuperDeal add-on, find nice deals and purchase them. 

Then, when the items come in the mail, we ask our pricing add-on where we should list it, and for how much gold pieces (possibly through a GUI). No more manual labour required!

**Comment by JordyMoos** [comment]
That makes perfectly sense. I was thinking about an addon that shows some statistics in the item tooltip that is showed when you hover over or click an item (for example in your inventory or in the guild store)

Some information that can be added there is:
How often is it sold last week
What is the suggested price over all guilds
Etc

If we do what you say and introduce a new addon that takes care of the suggested price calculations. Than this addon can also use your idea to display the suggested price in the tooltip.
(That makes it 2 new addon: Tooltip price, suggested price library [your plan])

Also when we want to sell an item (and drag it into the sell form)
Then we could ask your addon about: Oke im selling this item in this guild. What price do you suggest for this guild. And let some selling addon fill that in for us. Saves time again.
(Third addon: sale assistant?)

Api calls for your idea could be
getSuggestedPrice(item, [guildName])
That will return the suggested price for the item, by default based on all guilds. But if you fill in a guild name it will only use that guilds sales to get a price for it.

I gues we should also be able to add more then one algorithm to get a price like we do now in this addon.
Like: Cheapest, Median, Mode, Average with some knowledge about the age of the sale etc
Or is that mis placed?

If that kinda what you are aiming at or did i understand it wrong?

**Comment by marcusklaas** [comment]
Yes, that is exactly what I meant. The tooltip would be super sweet!

**Comment by JordyMoos** [comment]
So the price suggester does not only return a suggested price but also the guild name where the price is the best?

getSuggestedPrice(itemLink) -> { pricePerPiece = x, guildName = y }

?

**Comment by JordyMoos** [comment]
Mmm it has some flaws; if i get the average price or w/e then i do not know for what guild. While that price might be a good price for guild A it might be too high for guild B.

An option is to let the algorithms run itself for each guild. And then return the price of the guild that scores best. But that kinda leave all algorithms with way too less data

**Comment by marcusklaas** [comment]
How is this done currently actually?

I feel we should ask for a suitable price for every guild. Note that even though we ask for the price for 1 guild, this does not restrict the pricing api to only use the sales history for that guild!

**Comment by JordyMoos** [comment]
Currently we just get the cheapest/median/expensivest sale. And the sale has a guild name attached.

But with this setup we do not retrict ourselves to sales. So we can also get a average price. Which is not a sale just a price. 

The thing is that SuperDeal needs to know the guild where to sell it. The average price might be too high for guild A and even too less for guild B (where we can ask even more gold for the same item).

So yea we can get a total average price of an item. But it is more valuable for us if we know where we can sell it for most. That also what SuperDeal needs to know.

Any ideas on your end?

**Comment by marcusklaas** [comment]
Right, but if we get 5 suggested prices for your 5 guilds, can't we just pick the highest one and list our item there?

About the prices vs sales, that's something we could give our pricing api access to, right? It still can be as flexible as putting everything in JMSuperDeal.

I hope I am understanding you correctly...

**Comment by marcusklaas** [comment]
This is implemented now!
